/**
 * Datos de ejemplo del backoffice.
 *
 * Los tres productos, los tres transportistas y el envío SH-2024-8821 son los
 * de referencia del Hito 2. El resto amplía el escenario con los
 * transportistas reales de TrackFlow (FedEx) y más envíos para que el panel muestre
 * agregaciones con sentido. Cuando exista la API en /services, este archivo se
 * sustituye por llamadas a esa API.
 */
import type {
  Carrier,
  Product,
  Shipment,
} from "@trackflow/logic/types/models";

export const sampleProducts: Product[] = [
  {
    sku: "SHOE-BLK-42",
    name: "Zapatillas Negras Running - Talla 42",
    category: "Fashion",
    weightKg: 0.8,
    dimensions: { lengthCm: 35, widthCm: 22, heightCm: 12 },
    warehouse: "Los Angeles",
    stockQuantity: 45,
    minStockThreshold: 20,
    unitCostUSD: 35.0,
    isFragile: false,
    status: "Active",
  },
  {
    sku: "LAPTOP-DELL-15",
    name: "Laptop Dell 15 pulgadas",
    category: "Electronics",
    weightKg: 2.3,
    dimensions: { lengthCm: 40, widthCm: 28, heightCm: 3 },
    warehouse: "Zaragoza",
    stockQuantity: 8,
    minStockThreshold: 10,
    unitCostUSD: 650.0,
    isFragile: true,
    status: "Low stock",
  },
  {
    sku: "PERFUME-COCO-50",
    name: "Perfume Coco 50ml",
    category: "Cosmetics",
    weightKg: 0.3,
    dimensions: { lengthCm: 12, widthCm: 8, heightCm: 15 },
    warehouse: "Los Angeles",
    stockQuantity: 120,
    minStockThreshold: 30,
    unitCostUSD: 85.0,
    isFragile: true,
    status: "Active",
  },
  {
    sku: "LAMP-NORD-01",
    name: "Lámpara de mesa nórdica",
    category: "Home",
    weightKg: 3.6,
    dimensions: { lengthCm: 30, widthCm: 30, heightCm: 55 },
    warehouse: "Zaragoza",
    stockQuantity: 0,
    minStockThreshold: 5,
    unitCostUSD: 42.5,
    isFragile: true,
    status: "Out of stock",
  },
  {
    sku: "JACKET-DEN-M",
    name: "Chaqueta vaquera - Talla M",
    category: "Fashion",
    weightKg: 1.1,
    dimensions: { lengthCm: 40, widthCm: 30, heightCm: 8 },
    warehouse: "Zaragoza",
    stockQuantity: 64,
    minStockThreshold: 25,
    unitCostUSD: 48.0,
    isFragile: false,
    status: "Active",
  },
  {
    // Registro con errores a propósito: demuestra validateProduct en la UI.
    sku: "",
    name: "Pedido transcrito desde email (incompleto)",
    category: "Other",
    weightKg: 140,
    dimensions: { lengthCm: 60, widthCm: 0, heightCm: 40 },
    warehouse: "Los Angeles",
    stockQuantity: 12,
    minStockThreshold: 2,
    unitCostUSD: 0,
    isFragile: false,
    status: "Active",
  },
];

export const sampleCarriers: Carrier[] = [
  {
    id: "CAR-UPS",
    name: "UPS",
    operatesIn: ["United States"],
    baseRateUSD: 5.0,
    ratePerKgUSD: 1.2,
    ratePerKmUSD: 0.05,
    avgDeliveryDays: 3,
    onTimeRate: 88,
    maxWeightKg: 30,
    handlesFragile: true,
    acceptsPriority: ["Standard", "Express"],
  },
  {
    id: "CAR-SEUR",
    name: "SEUR",
    operatesIn: ["Spain"],
    baseRateUSD: 6.5,
    ratePerKgUSD: 1.5,
    ratePerKmUSD: 0.08,
    avgDeliveryDays: 2,
    onTimeRate: 92,
    maxWeightKg: 25,
    handlesFragile: true,
    acceptsPriority: ["Standard", "Express", "Same-day"],
  },
  {
    id: "CAR-DHL",
    name: "DHL Express",
    operatesIn: ["United States", "Spain"],
    baseRateUSD: 12.0,
    ratePerKgUSD: 2.0,
    ratePerKmUSD: 0.1,
    avgDeliveryDays: 1,
    onTimeRate: 95,
    maxWeightKg: 50,
    handlesFragile: true,
    acceptsPriority: ["Express", "Same-day"],
  },
  {
    id: "CAR-FEDEX",
    name: "FedEx",
    operatesIn: ["United States"],
    baseRateUSD: 5.5,
    ratePerKgUSD: 1.1,
    ratePerKmUSD: 0.06,
    avgDeliveryDays: 2,
    onTimeRate: 90,
    maxWeightKg: 40,
    handlesFragile: false,
    acceptsPriority: ["Standard", "Express", "Same-day"],
  },
  {
    id: "CAR-MRW",
    name: "MRW",
    operatesIn: ["Spain"],
    baseRateUSD: 4.8,
    ratePerKgUSD: 1.3,
    ratePerKmUSD: 0.07,
    avgDeliveryDays: 2,
    onTimeRate: 84,
    maxWeightKg: 30,
    handlesFragile: false,
    acceptsPriority: ["Standard", "Express"],
  },
];

export const sampleShipments: Shipment[] = [
  {
    id: "SH-2024-8821",
    sku: "LAPTOP-DELL-15",
    quantity: 1,
    origin: "Zaragoza",
    destination: {
      city: "Madrid",
      country: "Spain",
      postalCode: "28001",
      distanceKm: 320,
    },
    priority: "Express",
    declaredValueUSD: 650.0,
    carrier: null,
    status: "Pending",
    createdAt: new Date("2024-03-15"),
  },
  {
    id: "SH-2024-8822",
    sku: "SHOE-BLK-42",
    quantity: 2,
    origin: "Los Angeles",
    destination: {
      city: "San Diego",
      country: "United States",
      postalCode: "92101",
      distanceKm: 195,
    },
    priority: "Standard",
    declaredValueUSD: 70.0,
    carrier: "UPS",
    status: "In transit",
    createdAt: new Date("2024-03-15"),
  },
  {
    id: "SH-2024-8823",
    sku: "PERFUME-COCO-50",
    quantity: 3,
    origin: "Los Angeles",
    destination: {
      city: "Las Vegas",
      country: "United States",
      postalCode: "89101",
      distanceKm: 435,
    },
    priority: "Express",
    declaredValueUSD: 255.0,
    carrier: "UPS",
    status: "Delivered",
    createdAt: new Date("2024-03-14"),
  },
  {
    id: "SH-2024-8824",
    sku: "JACKET-DEN-M",
    quantity: 1,
    origin: "Zaragoza",
    destination: {
      city: "Barcelona",
      country: "Spain",
      postalCode: "08001",
      distanceKm: 296,
    },
    priority: "Standard",
    declaredValueUSD: 48.0,
    carrier: "SEUR",
    status: "Delivered",
    createdAt: new Date("2024-03-13"),
  },
  {
    id: "SH-2024-8825",
    sku: "LAPTOP-DELL-15",
    quantity: 1,
    origin: "Zaragoza",
    destination: {
      city: "Valencia",
      country: "Spain",
      postalCode: "46001",
      distanceKm: 309,
    },
    priority: "Same-day",
    declaredValueUSD: 650.0,
    carrier: "SEUR",
    status: "Assigned",
    createdAt: new Date("2024-03-15"),
  },
  {
    id: "SH-2024-8826",
    sku: "SHOE-BLK-42",
    quantity: 1,
    origin: "Los Angeles",
    destination: {
      city: "Phoenix",
      country: "United States",
      postalCode: "85001",
      distanceKm: 600,
    },
    priority: "Standard",
    declaredValueUSD: 35.0,
    carrier: "FedEx",
    status: "Failed",
    createdAt: new Date("2024-03-12"),
  },
  {
    id: "SH-2024-8827",
    sku: "PERFUME-COCO-50",
    quantity: 1,
    origin: "Los Angeles",
    destination: {
      city: "Los Angeles",
      country: "United States",
      postalCode: "90012",
      distanceKm: 18,
    },
    priority: "Same-day",
    declaredValueUSD: 85.0,
    carrier: "DHL Express",
    status: "Delivered",
    createdAt: new Date("2024-03-15"),
  },
  {
    // Registro con errores a propósito: demuestra validateShipment en la UI.
    id: "SH-2024-8828",
    sku: "JACKET-DEN-M",
    quantity: 0,
    origin: "Zaragoza",
    destination: {
      city: "Huesca",
      country: "Spain",
      postalCode: "22001",
      distanceKm: -70,
    },
    priority: "Standard",
    declaredValueUSD: 0,
    carrier: null,
    status: "Pending",
    createdAt: new Date("2024-03-15"),
  },
];
